version: "3"

services:
  synapse:
    build:
      context: .config/acter-synapse-ci
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./.local/docker-data:/data:rw
    ports:
      - 8448:8448/tcp
      - 8118:8008/tcp

  setup-admin:
    build:
      context: .config/acter-synapse-ci
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./.local/docker-data:/data:ro
    links:
      - synapse
    entrypoint: "/bin/bash -c"
    command: '"register_new_matrix_user -u admin -p admin -a -c /data/homeserver.yaml http://synapse:8008"'
