services:
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  share_links_ownership:
    image: alpine
    user: root
    volumes:
      - ./.local/share_links:/share_links
    command: chmod 777 /share_links
    restart: none

  synapse:
    build:
      context: .config/acter-synapse-ci
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./.local/docker-data:/data:rw
      - ./.local/share_links:/share_links
    ports:
      - 8448:8448/tcp
      - 8118:8008/tcp
    depends_on:
      - share_links_ownership

  web:
    image: nginx
    restart: on-failure
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.local/share_links/:/app/static/:ro
    ports:
      - 8099:8099/tcp
    depends_on:
      - share_links_ownership

  rageshake:
    image: "ghcr.io/matrix-org/rageshake"
    restart: unless-stopped
    user: root
    volumes:
      - ./.config/rageshake.yml:/rageshake.yml
      - type: tmpfs
        target: /bugs/
        tmpfs:
          mode: 777
    command: "-config /rageshake.yml"
    ports:
      - 9110:9110/tcp

  setup-admin:
    build:
      context: .config/acter-synapse-ci
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./.local/docker-data:/data:ro
    links:
      - synapse
    entrypoint: "/bin/bash -c"
    command: '"register_new_matrix_user -u admin -p admin -a -c /data/homeserver.yaml http://synapse:8008"'
