name: example
description: Exmaple project for riverpod_infinite_scroll
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod_infinite_scroll:
    path: ../../riverpod_infinite_scroll

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
