include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_use_package_imports: true
    file_names: false

analyzer:
  exclude:
    - lib/acter_flutter_sdk_ffi.dart
    - lib/acter.dart

