import 'package:acter/features/chat_ui_showcase/models/convo_showcase_data.dart';

final List<MockChatItem> mockChatList = [
  emilyDmMutedBookmarkedRoom1,
  productTeamMutedWithSingleTypingUserRoom2,
  engineeringTeamWithTestUpdateRoom3,
  designReviewMutedBookmarkedWithUnreadRoom4,
  groupDmWithMichaelKumarpalsinhBenRoom5,
  sarahDmWithTypingRoom6,
  projectAlphaWithMultipleTypingRoom7,
  lisaDmBookmarkedImageMessageRoom8,
  teamUpdatesBookmarkedVideoMessageRoom9,
  groupDmWithEmmaKumarpalsinhBenRoom10,
  alexDmRoom11,
  marketingTeamRoom12,
  lisaDmRoom13,
  productFeedbackGroupRoom14,
  davidDmRoom15,
  imageMessageDmRoom16,
  videoMessageDmRoom17,
  audioMessageDmRoom18,
  fileMessageDmRoom19,
  locationMessageDmRoom20,
  redactionEventRoom21,
];
