arb-dir: lib/l10n
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: L10n
preferred-supported-locales: ["en"]
nullable-getter: false
synthetic-package: false