name: riverpod_infinite_scroll
description: Riverpod implementation of infinite_scroll_pagination, this package
  allows to use infinite_scroll_pagination with Riverpod abstracting away the
  complexity
version: 1.0.9
homepage: https://www.quantos.it
repository: https://github.com/ftognetto/riverpod_infinite_scroll
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ">=2.0.0 <=2.4.4"
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
