#import <Flutter/Flutter.h>

@interface EffektioFlutterSdkPlugin : NSObject<FlutterPlugin>
@end



/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef struct _FfiStringParts {
  int64_t ptr;
  uint64_t len;
  uint64_t capacity;
} _FfiStringParts;

typedef struct __init_loggingReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __init_loggingReturn;

typedef struct __Color_rgba_u8Return {
  uint8_t ret0;
  uint8_t ret1;
  uint8_t ret2;
  uint8_t ret3;
} __Color_rgba_u8Return;

typedef struct __News_textReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __News_textReturn;

typedef struct __News_fg_colorReturn {
  uint8_t ret0;
  int64_t ret1;
} __News_fg_colorReturn;

typedef struct __News_bg_colorReturn {
  uint8_t ret0;
  int64_t ret1;
} __News_bg_colorReturn;

typedef struct __News_imageReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __News_imageReturn;

typedef struct __Tag_titleReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __Tag_titleReturn;

typedef struct __Tag_hash_tagReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __Tag_hash_tagReturn;

typedef struct __Tag_colorReturn {
  uint8_t ret0;
  int64_t ret1;
} __Tag_colorReturn;

typedef struct __Faq_titleReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __Faq_titleReturn;

typedef struct __Faq_bodyReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __Faq_bodyReturn;

typedef struct __UserId_to_stringReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __UserId_to_stringReturn;

typedef struct __RoomMessage_event_idReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __RoomMessage_event_idReturn;

typedef struct __RoomMessage_senderReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __RoomMessage_senderReturn;

typedef struct __RoomMessage_bodyReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __RoomMessage_bodyReturn;

typedef struct __RoomMessage_msgtypeReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __RoomMessage_msgtypeReturn;

typedef struct __RoomMessage_image_descriptionReturn {
  uint8_t ret0;
  int64_t ret1;
} __RoomMessage_image_descriptionReturn;

typedef struct __RoomMessage_file_descriptionReturn {
  uint8_t ret0;
  int64_t ret1;
} __RoomMessage_file_descriptionReturn;

typedef struct __ImageDescription_nameReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __ImageDescription_nameReturn;

typedef struct __ImageDescription_mimetypeReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __ImageDescription_mimetypeReturn;

typedef struct __ImageDescription_sizeReturn {
  uint8_t ret0;
  uint64_t ret1;
} __ImageDescription_sizeReturn;

typedef struct __ImageDescription_widthReturn {
  uint8_t ret0;
  uint64_t ret1;
} __ImageDescription_widthReturn;

typedef struct __ImageDescription_heightReturn {
  uint8_t ret0;
  uint64_t ret1;
} __ImageDescription_heightReturn;

typedef struct __FileDescription_nameReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __FileDescription_nameReturn;

typedef struct __FileDescription_mimetypeReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __FileDescription_mimetypeReturn;

typedef struct __FileDescription_sizeReturn {
  uint8_t ret0;
  uint64_t ret1;
} __FileDescription_sizeReturn;

typedef struct __Member_display_nameReturn {
  uint8_t ret0;
  int64_t ret1;
  uint64_t ret2;
  uint64_t ret3;
} __Member_display_nameReturn;

typedef struct __SyncState_get_to_device_rxReturn {
  uint8_t ret0;
  int64_t ret1;
} __SyncState_get_to_device_rxReturn;

typedef struct __SyncState_get_sync_msg_like_rxReturn {
  uint8_t ret0;
  int64_t ret1;
} __SyncState_get_sync_msg_like_rxReturn;

typedef struct __CrossSigningEvent_get_event_nameReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __CrossSigningEvent_get_event_nameReturn;

typedef struct __CrossSigningEvent_get_event_idReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __CrossSigningEvent_get_event_idReturn;

typedef struct __CrossSigningEvent_get_senderReturn {
  int64_t ret0;
  uint64_t ret1;
  uint64_t ret2;
} __CrossSigningEvent_get_senderReturn;

typedef struct __login_new_client_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __login_new_client_future_pollReturn;

typedef struct __login_with_token_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __login_with_token_future_pollReturn;

typedef struct __guest_client_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __guest_client_future_pollReturn;

typedef struct __register_with_registration_token_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __register_with_registration_token_future_pollReturn;

typedef struct __TimelineStream_next_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __TimelineStream_next_future_pollReturn;

typedef struct __TimelineStream_paginate_backwards_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __TimelineStream_paginate_backwards_future_pollReturn;

typedef struct __Conversation_display_name_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_display_name_future_pollReturn;

typedef struct __Conversation_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_avatar_future_pollReturn;

typedef struct __Conversation_active_members_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_active_members_future_pollReturn;

typedef struct __Conversation_timeline_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_timeline_future_pollReturn;

typedef struct __Conversation_get_member_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_get_member_future_pollReturn;

typedef struct __Conversation_latest_message_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_latest_message_future_pollReturn;

typedef struct __Conversation_typing_notice_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Conversation_typing_notice_future_pollReturn;

typedef struct __Conversation_read_receipt_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Conversation_read_receipt_future_pollReturn;

typedef struct __Conversation_send_plain_message_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_send_plain_message_future_pollReturn;

typedef struct __Conversation_send_image_message_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_send_image_message_future_pollReturn;

typedef struct __Conversation_image_binary_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Conversation_image_binary_future_pollReturn;

typedef struct __Conversation_send_file_message_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_send_file_message_future_pollReturn;

typedef struct __Conversation_save_file_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_save_file_future_pollReturn;

typedef struct __Conversation_file_path_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Conversation_file_path_future_pollReturn;

typedef struct __Group_display_name_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Group_display_name_future_pollReturn;

typedef struct __Group_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Group_avatar_future_pollReturn;

typedef struct __Group_active_members_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Group_active_members_future_pollReturn;

typedef struct __Group_get_member_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Group_get_member_future_pollReturn;

typedef struct __Member_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Member_avatar_future_pollReturn;

typedef struct __Account_display_name_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Account_display_name_future_pollReturn;

typedef struct __Account_set_display_name_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Account_set_display_name_future_pollReturn;

typedef struct __Account_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Account_avatar_future_pollReturn;

typedef struct __Account_set_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Account_set_avatar_future_pollReturn;

typedef struct __Client_restore_token_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Client_restore_token_future_pollReturn;

typedef struct __Client_account_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_account_future_pollReturn;

typedef struct __Client_device_id_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Client_device_id_future_pollReturn;

typedef struct __Client_user_id_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_user_id_future_pollReturn;

typedef struct __Client_display_name_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Client_display_name_future_pollReturn;

typedef struct __Client_avatar_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_avatar_future_pollReturn;

typedef struct __Client_conversations_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_conversations_future_pollReturn;

typedef struct __Client_groups_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_groups_future_pollReturn;

typedef struct __Client_latest_news_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_latest_news_future_pollReturn;

typedef struct __Client_faqs_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
} __Client_faqs_future_pollReturn;

typedef struct __Client_accept_verification_request_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_accept_verification_request_future_pollReturn;

typedef struct __Client_accept_verification_start_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_accept_verification_start_future_pollReturn;

typedef struct __Client_get_verification_emoji_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  int64_t ret5;
  uint64_t ret6;
  uint64_t ret7;
} __Client_get_verification_emoji_future_pollReturn;

typedef struct __Client_confirm_verification_key_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_confirm_verification_key_future_pollReturn;

typedef struct __Client_mismatch_verification_key_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_mismatch_verification_key_future_pollReturn;

typedef struct __Client_cancel_verification_key_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_cancel_verification_key_future_pollReturn;

typedef struct __Client_review_verification_mac_future_pollReturn {
  uint8_t ret0;
  uint8_t ret1;
  int64_t ret2;
  uint64_t ret3;
  uint64_t ret4;
  uint8_t ret5;
} __Client_review_verification_mac_future_pollReturn;

typedef struct __SyncState_get_to_device_rx_stream_pollReturn {
  uint8_t ret0;
  int64_t ret1;
} __SyncState_get_to_device_rx_stream_pollReturn;

typedef struct __SyncState_get_sync_msg_like_rx_stream_pollReturn {
  uint8_t ret0;
  int64_t ret1;
} __SyncState_get_sync_msg_like_rx_stream_pollReturn;

uint8_t *allocate(uintptr_t size, uintptr_t align);

void deallocate(uint8_t *ptr, uintptr_t size, uintptr_t align);

void *__ffi_buffer_address(void *ptr);

uint64_t __ffi_buffer_size(void *ptr);

struct _FfiStringParts __ffi_string_into_parts(void *ptr);

void drop_box_FfiBuffer(int64_t, int64_t boxed);

void drop_box_Leak(int64_t, int64_t boxed);

struct __init_loggingReturn __init_logging(uint8_t tmp1,
                                           int64_t tmp3,
                                           uint64_t tmp4,
                                           uint64_t tmp5);

int64_t __login_new_client(int64_t tmp1,
                           uint64_t tmp2,
                           uint64_t tmp3,
                           int64_t tmp5,
                           uint64_t tmp6,
                           uint64_t tmp7,
                           int64_t tmp9,
                           uint64_t tmp10,
                           uint64_t tmp11);

int64_t __login_with_token(int64_t tmp1,
                           uint64_t tmp2,
                           uint64_t tmp3,
                           int64_t tmp5,
                           uint64_t tmp6,
                           uint64_t tmp7);

int64_t __guest_client(int64_t tmp1,
                       uint64_t tmp2,
                       uint64_t tmp3,
                       int64_t tmp5,
                       uint64_t tmp6,
                       uint64_t tmp7);

int64_t __register_with_registration_token(int64_t tmp1,
                                           uint64_t tmp2,
                                           uint64_t tmp3,
                                           int64_t tmp5,
                                           uint64_t tmp6,
                                           uint64_t tmp7,
                                           int64_t tmp9,
                                           uint64_t tmp10,
                                           uint64_t tmp11,
                                           int64_t tmp13,
                                           uint64_t tmp14,
                                           uint64_t tmp15);

int64_t __gen_mock_news(void);

struct __Color_rgba_u8Return __Color_rgba_u8(int64_t tmp1);

void drop_box_Color(int64_t, int64_t boxed);

struct __News_textReturn __News_text(int64_t tmp1);

int64_t __News_tags(int64_t tmp1);

uint32_t __News_likes_count(int64_t tmp1);

uint32_t __News_comments_count(int64_t tmp1);

struct __News_fg_colorReturn __News_fg_color(int64_t tmp1);

struct __News_bg_colorReturn __News_bg_color(int64_t tmp1);

struct __News_imageReturn __News_image(int64_t tmp1);

void drop_box_News(int64_t, int64_t boxed);

struct __Tag_titleReturn __Tag_title(int64_t tmp1);

struct __Tag_hash_tagReturn __Tag_hash_tag(int64_t tmp1);

struct __Tag_colorReturn __Tag_color(int64_t tmp1);

void drop_box_Tag(int64_t, int64_t boxed);

struct __Faq_titleReturn __Faq_title(int64_t tmp1);

struct __Faq_bodyReturn __Faq_body(int64_t tmp1);

uint8_t __Faq_pinned(int64_t tmp1);

int64_t __Faq_tags(int64_t tmp1);

uint32_t __Faq_likes_count(int64_t tmp1);

uint32_t __Faq_comments_count(int64_t tmp1);

void drop_box_Faq(int64_t, int64_t boxed);

struct __UserId_to_stringReturn __UserId_to_string(int64_t tmp1);

void drop_box_UserId(int64_t, int64_t boxed);

void drop_box_EventId(int64_t, int64_t boxed);

struct __RoomMessage_event_idReturn __RoomMessage_event_id(int64_t tmp1);

struct __RoomMessage_senderReturn __RoomMessage_sender(int64_t tmp1);

struct __RoomMessage_bodyReturn __RoomMessage_body(int64_t tmp1);

uint64_t __RoomMessage_origin_server_ts(int64_t tmp1);

struct __RoomMessage_msgtypeReturn __RoomMessage_msgtype(int64_t tmp1);

struct __RoomMessage_image_descriptionReturn __RoomMessage_image_description(int64_t tmp1);

struct __RoomMessage_file_descriptionReturn __RoomMessage_file_description(int64_t tmp1);

void drop_box_RoomMessage(int64_t, int64_t boxed);

struct __ImageDescription_nameReturn __ImageDescription_name(int64_t tmp1);

struct __ImageDescription_mimetypeReturn __ImageDescription_mimetype(int64_t tmp1);

struct __ImageDescription_sizeReturn __ImageDescription_size(int64_t tmp1);

struct __ImageDescription_widthReturn __ImageDescription_width(int64_t tmp1);

struct __ImageDescription_heightReturn __ImageDescription_height(int64_t tmp1);

void drop_box_ImageDescription(int64_t, int64_t boxed);

struct __FileDescription_nameReturn __FileDescription_name(int64_t tmp1);

struct __FileDescription_mimetypeReturn __FileDescription_mimetype(int64_t tmp1);

struct __FileDescription_sizeReturn __FileDescription_size(int64_t tmp1);

void drop_box_FileDescription(int64_t, int64_t boxed);

int64_t __TimelineStream_next(int64_t tmp1);

int64_t __TimelineStream_paginate_backwards(int64_t tmp1, uint64_t tmp3);

void drop_box_TimelineStream(int64_t, int64_t boxed);

int64_t __Conversation_display_name(int64_t tmp1);

int64_t __Conversation_avatar(int64_t tmp1);

int64_t __Conversation_active_members(int64_t tmp1);

int64_t __Conversation_timeline(int64_t tmp1);

int64_t __Conversation_get_member(int64_t tmp1, int64_t tmp3);

int64_t __Conversation_latest_message(int64_t tmp1);

int64_t __Conversation_typing_notice(int64_t tmp1, uint8_t tmp3);

int64_t __Conversation_read_receipt(int64_t tmp1, int64_t tmp3, uint64_t tmp4, uint64_t tmp5);

int64_t __Conversation_send_plain_message(int64_t tmp1, int64_t tmp3, uint64_t tmp4, uint64_t tmp5);

int64_t __Conversation_send_image_message(int64_t tmp1,
                                          int64_t tmp3,
                                          uint64_t tmp4,
                                          uint64_t tmp5,
                                          int64_t tmp7,
                                          uint64_t tmp8,
                                          uint64_t tmp9,
                                          int64_t tmp11,
                                          uint64_t tmp12,
                                          uint64_t tmp13,
                                          uint8_t tmp15,
                                          uint32_t tmp17,
                                          uint8_t tmp19,
                                          uint32_t tmp21,
                                          uint8_t tmp23,
                                          uint32_t tmp25);

int64_t __Conversation_image_binary(int64_t tmp1, int64_t tmp3, uint64_t tmp4, uint64_t tmp5);

int64_t __Conversation_send_file_message(int64_t tmp1,
                                         int64_t tmp3,
                                         uint64_t tmp4,
                                         uint64_t tmp5,
                                         int64_t tmp7,
                                         uint64_t tmp8,
                                         uint64_t tmp9,
                                         int64_t tmp11,
                                         uint64_t tmp12,
                                         uint64_t tmp13,
                                         uint32_t tmp15);

int64_t __Conversation_save_file(int64_t tmp1,
                                 int64_t tmp3,
                                 uint64_t tmp4,
                                 uint64_t tmp5,
                                 int64_t tmp7,
                                 uint64_t tmp8,
                                 uint64_t tmp9);

int64_t __Conversation_file_path(int64_t tmp1, int64_t tmp3, uint64_t tmp4, uint64_t tmp5);

void drop_box_Conversation(int64_t, int64_t boxed);

int64_t __Group_display_name(int64_t tmp1);

int64_t __Group_avatar(int64_t tmp1);

int64_t __Group_active_members(int64_t tmp1);

int64_t __Group_get_member(int64_t tmp1, int64_t tmp3);

void drop_box_Group(int64_t, int64_t boxed);

int64_t __Member_avatar(int64_t tmp1);

struct __Member_display_nameReturn __Member_display_name(int64_t tmp1);

int64_t __Member_user_id(int64_t tmp1);

void drop_box_Member(int64_t, int64_t boxed);

int64_t __Account_display_name(int64_t tmp1);

int64_t __Account_set_display_name(int64_t tmp1, int64_t tmp3, uint64_t tmp4, uint64_t tmp5);

int64_t __Account_avatar(int64_t tmp1);

int64_t __Account_set_avatar(int64_t tmp1,
                             int64_t tmp3,
                             uint64_t tmp4,
                             uint64_t tmp5,
                             int64_t tmp7,
                             uint64_t tmp8,
                             uint64_t tmp9);

void drop_box_Account(int64_t, int64_t boxed);

struct __SyncState_get_to_device_rxReturn __SyncState_get_to_device_rx(int64_t tmp1);

struct __SyncState_get_sync_msg_like_rxReturn __SyncState_get_sync_msg_like_rx(int64_t tmp1);

void drop_box_SyncState(int64_t, int64_t boxed);

int64_t __Client_start_sync(int64_t tmp1);

int64_t __Client_restore_token(int64_t tmp1);

uint8_t __Client_is_guest(int64_t tmp1);

uint8_t __Client_has_first_synced(int64_t tmp1);

uint8_t __Client_is_syncing(int64_t tmp1);

uint8_t __Client_logged_in(int64_t tmp1);

int64_t __Client_account(int64_t tmp1);

int64_t __Client_device_id(int64_t tmp1);

int64_t __Client_user_id(int64_t tmp1);

int64_t __Client_display_name(int64_t tmp1);

int64_t __Client_avatar(int64_t tmp1);

int64_t __Client_conversations(int64_t tmp1);

int64_t __Client_groups(int64_t tmp1);

int64_t __Client_latest_news(int64_t tmp1);

int64_t __Client_faqs(int64_t tmp1);

int64_t __Client_accept_verification_request(int64_t tmp1,
                                             int64_t tmp3,
                                             uint64_t tmp4,
                                             uint64_t tmp5,
                                             int64_t tmp7,
                                             uint64_t tmp8,
                                             uint64_t tmp9);

int64_t __Client_accept_verification_start(int64_t tmp1,
                                           int64_t tmp3,
                                           uint64_t tmp4,
                                           uint64_t tmp5,
                                           int64_t tmp7,
                                           uint64_t tmp8,
                                           uint64_t tmp9);

int64_t __Client_get_verification_emoji(int64_t tmp1,
                                        int64_t tmp3,
                                        uint64_t tmp4,
                                        uint64_t tmp5,
                                        int64_t tmp7,
                                        uint64_t tmp8,
                                        uint64_t tmp9);

int64_t __Client_confirm_verification_key(int64_t tmp1,
                                          int64_t tmp3,
                                          uint64_t tmp4,
                                          uint64_t tmp5,
                                          int64_t tmp7,
                                          uint64_t tmp8,
                                          uint64_t tmp9);

int64_t __Client_mismatch_verification_key(int64_t tmp1,
                                           int64_t tmp3,
                                           uint64_t tmp4,
                                           uint64_t tmp5,
                                           int64_t tmp7,
                                           uint64_t tmp8,
                                           uint64_t tmp9);

int64_t __Client_cancel_verification_key(int64_t tmp1,
                                         int64_t tmp3,
                                         uint64_t tmp4,
                                         uint64_t tmp5,
                                         int64_t tmp7,
                                         uint64_t tmp8,
                                         uint64_t tmp9);

int64_t __Client_review_verification_mac(int64_t tmp1,
                                         int64_t tmp3,
                                         uint64_t tmp4,
                                         uint64_t tmp5,
                                         int64_t tmp7,
                                         uint64_t tmp8,
                                         uint64_t tmp9);

void drop_box_Client(int64_t, int64_t boxed);

struct __CrossSigningEvent_get_event_nameReturn __CrossSigningEvent_get_event_name(int64_t tmp1);

struct __CrossSigningEvent_get_event_idReturn __CrossSigningEvent_get_event_id(int64_t tmp1);

struct __CrossSigningEvent_get_senderReturn __CrossSigningEvent_get_sender(int64_t tmp1);

void drop_box_CrossSigningEvent(int64_t, int64_t boxed);

struct __login_new_client_future_pollReturn __login_new_client_future_poll(int64_t tmp1,
                                                                           int64_t tmp3,
                                                                           int64_t tmp5);

void __login_new_client_future_drop(int64_t, int64_t boxed);

struct __login_with_token_future_pollReturn __login_with_token_future_poll(int64_t tmp1,
                                                                           int64_t tmp3,
                                                                           int64_t tmp5);

void __login_with_token_future_drop(int64_t, int64_t boxed);

struct __guest_client_future_pollReturn __guest_client_future_poll(int64_t tmp1,
                                                                   int64_t tmp3,
                                                                   int64_t tmp5);

void __guest_client_future_drop(int64_t, int64_t boxed);

struct __register_with_registration_token_future_pollReturn __register_with_registration_token_future_poll(int64_t tmp1,
                                                                                                           int64_t tmp3,
                                                                                                           int64_t tmp5);

void __register_with_registration_token_future_drop(int64_t, int64_t boxed);

struct __TimelineStream_next_future_pollReturn __TimelineStream_next_future_poll(int64_t tmp1,
                                                                                 int64_t tmp3,
                                                                                 int64_t tmp5);

void __TimelineStream_next_future_drop(int64_t, int64_t boxed);

struct __TimelineStream_paginate_backwards_future_pollReturn __TimelineStream_paginate_backwards_future_poll(int64_t tmp1,
                                                                                                             int64_t tmp3,
                                                                                                             int64_t tmp5);

void __TimelineStream_paginate_backwards_future_drop(int64_t, int64_t boxed);

struct __Conversation_display_name_future_pollReturn __Conversation_display_name_future_poll(int64_t tmp1,
                                                                                             int64_t tmp3,
                                                                                             int64_t tmp5);

void __Conversation_display_name_future_drop(int64_t, int64_t boxed);

struct __Conversation_avatar_future_pollReturn __Conversation_avatar_future_poll(int64_t tmp1,
                                                                                 int64_t tmp3,
                                                                                 int64_t tmp5);

void __Conversation_avatar_future_drop(int64_t, int64_t boxed);

struct __Conversation_active_members_future_pollReturn __Conversation_active_members_future_poll(int64_t tmp1,
                                                                                                 int64_t tmp3,
                                                                                                 int64_t tmp5);

void __Conversation_active_members_future_drop(int64_t, int64_t boxed);

struct __Conversation_timeline_future_pollReturn __Conversation_timeline_future_poll(int64_t tmp1,
                                                                                     int64_t tmp3,
                                                                                     int64_t tmp5);

void __Conversation_timeline_future_drop(int64_t, int64_t boxed);

struct __Conversation_get_member_future_pollReturn __Conversation_get_member_future_poll(int64_t tmp1,
                                                                                         int64_t tmp3,
                                                                                         int64_t tmp5);

void __Conversation_get_member_future_drop(int64_t, int64_t boxed);

struct __Conversation_latest_message_future_pollReturn __Conversation_latest_message_future_poll(int64_t tmp1,
                                                                                                 int64_t tmp3,
                                                                                                 int64_t tmp5);

void __Conversation_latest_message_future_drop(int64_t, int64_t boxed);

struct __Conversation_typing_notice_future_pollReturn __Conversation_typing_notice_future_poll(int64_t tmp1,
                                                                                               int64_t tmp3,
                                                                                               int64_t tmp5);

void __Conversation_typing_notice_future_drop(int64_t, int64_t boxed);

struct __Conversation_read_receipt_future_pollReturn __Conversation_read_receipt_future_poll(int64_t tmp1,
                                                                                             int64_t tmp3,
                                                                                             int64_t tmp5);

void __Conversation_read_receipt_future_drop(int64_t, int64_t boxed);

struct __Conversation_send_plain_message_future_pollReturn __Conversation_send_plain_message_future_poll(int64_t tmp1,
                                                                                                         int64_t tmp3,
                                                                                                         int64_t tmp5);

void __Conversation_send_plain_message_future_drop(int64_t, int64_t boxed);

struct __Conversation_send_image_message_future_pollReturn __Conversation_send_image_message_future_poll(int64_t tmp1,
                                                                                                         int64_t tmp3,
                                                                                                         int64_t tmp5);

void __Conversation_send_image_message_future_drop(int64_t, int64_t boxed);

struct __Conversation_image_binary_future_pollReturn __Conversation_image_binary_future_poll(int64_t tmp1,
                                                                                             int64_t tmp3,
                                                                                             int64_t tmp5);

void __Conversation_image_binary_future_drop(int64_t, int64_t boxed);

struct __Conversation_send_file_message_future_pollReturn __Conversation_send_file_message_future_poll(int64_t tmp1,
                                                                                                       int64_t tmp3,
                                                                                                       int64_t tmp5);

void __Conversation_send_file_message_future_drop(int64_t, int64_t boxed);

struct __Conversation_save_file_future_pollReturn __Conversation_save_file_future_poll(int64_t tmp1,
                                                                                       int64_t tmp3,
                                                                                       int64_t tmp5);

void __Conversation_save_file_future_drop(int64_t, int64_t boxed);

struct __Conversation_file_path_future_pollReturn __Conversation_file_path_future_poll(int64_t tmp1,
                                                                                       int64_t tmp3,
                                                                                       int64_t tmp5);

void __Conversation_file_path_future_drop(int64_t, int64_t boxed);

struct __Group_display_name_future_pollReturn __Group_display_name_future_poll(int64_t tmp1,
                                                                               int64_t tmp3,
                                                                               int64_t tmp5);

void __Group_display_name_future_drop(int64_t, int64_t boxed);

struct __Group_avatar_future_pollReturn __Group_avatar_future_poll(int64_t tmp1,
                                                                   int64_t tmp3,
                                                                   int64_t tmp5);

void __Group_avatar_future_drop(int64_t, int64_t boxed);

struct __Group_active_members_future_pollReturn __Group_active_members_future_poll(int64_t tmp1,
                                                                                   int64_t tmp3,
                                                                                   int64_t tmp5);

void __Group_active_members_future_drop(int64_t, int64_t boxed);

struct __Group_get_member_future_pollReturn __Group_get_member_future_poll(int64_t tmp1,
                                                                           int64_t tmp3,
                                                                           int64_t tmp5);

void __Group_get_member_future_drop(int64_t, int64_t boxed);

struct __Member_avatar_future_pollReturn __Member_avatar_future_poll(int64_t tmp1,
                                                                     int64_t tmp3,
                                                                     int64_t tmp5);

void __Member_avatar_future_drop(int64_t, int64_t boxed);

struct __Account_display_name_future_pollReturn __Account_display_name_future_poll(int64_t tmp1,
                                                                                   int64_t tmp3,
                                                                                   int64_t tmp5);

void __Account_display_name_future_drop(int64_t, int64_t boxed);

struct __Account_set_display_name_future_pollReturn __Account_set_display_name_future_poll(int64_t tmp1,
                                                                                           int64_t tmp3,
                                                                                           int64_t tmp5);

void __Account_set_display_name_future_drop(int64_t, int64_t boxed);

struct __Account_avatar_future_pollReturn __Account_avatar_future_poll(int64_t tmp1,
                                                                       int64_t tmp3,
                                                                       int64_t tmp5);

void __Account_avatar_future_drop(int64_t, int64_t boxed);

struct __Account_set_avatar_future_pollReturn __Account_set_avatar_future_poll(int64_t tmp1,
                                                                               int64_t tmp3,
                                                                               int64_t tmp5);

void __Account_set_avatar_future_drop(int64_t, int64_t boxed);

struct __Client_restore_token_future_pollReturn __Client_restore_token_future_poll(int64_t tmp1,
                                                                                   int64_t tmp3,
                                                                                   int64_t tmp5);

void __Client_restore_token_future_drop(int64_t, int64_t boxed);

struct __Client_account_future_pollReturn __Client_account_future_poll(int64_t tmp1,
                                                                       int64_t tmp3,
                                                                       int64_t tmp5);

void __Client_account_future_drop(int64_t, int64_t boxed);

struct __Client_device_id_future_pollReturn __Client_device_id_future_poll(int64_t tmp1,
                                                                           int64_t tmp3,
                                                                           int64_t tmp5);

void __Client_device_id_future_drop(int64_t, int64_t boxed);

struct __Client_user_id_future_pollReturn __Client_user_id_future_poll(int64_t tmp1,
                                                                       int64_t tmp3,
                                                                       int64_t tmp5);

void __Client_user_id_future_drop(int64_t, int64_t boxed);

struct __Client_display_name_future_pollReturn __Client_display_name_future_poll(int64_t tmp1,
                                                                                 int64_t tmp3,
                                                                                 int64_t tmp5);

void __Client_display_name_future_drop(int64_t, int64_t boxed);

struct __Client_avatar_future_pollReturn __Client_avatar_future_poll(int64_t tmp1,
                                                                     int64_t tmp3,
                                                                     int64_t tmp5);

void __Client_avatar_future_drop(int64_t, int64_t boxed);

struct __Client_conversations_future_pollReturn __Client_conversations_future_poll(int64_t tmp1,
                                                                                   int64_t tmp3,
                                                                                   int64_t tmp5);

void __Client_conversations_future_drop(int64_t, int64_t boxed);

struct __Client_groups_future_pollReturn __Client_groups_future_poll(int64_t tmp1,
                                                                     int64_t tmp3,
                                                                     int64_t tmp5);

void __Client_groups_future_drop(int64_t, int64_t boxed);

struct __Client_latest_news_future_pollReturn __Client_latest_news_future_poll(int64_t tmp1,
                                                                               int64_t tmp3,
                                                                               int64_t tmp5);

void __Client_latest_news_future_drop(int64_t, int64_t boxed);

struct __Client_faqs_future_pollReturn __Client_faqs_future_poll(int64_t tmp1,
                                                                 int64_t tmp3,
                                                                 int64_t tmp5);

void __Client_faqs_future_drop(int64_t, int64_t boxed);

struct __Client_accept_verification_request_future_pollReturn __Client_accept_verification_request_future_poll(int64_t tmp1,
                                                                                                               int64_t tmp3,
                                                                                                               int64_t tmp5);

void __Client_accept_verification_request_future_drop(int64_t, int64_t boxed);

struct __Client_accept_verification_start_future_pollReturn __Client_accept_verification_start_future_poll(int64_t tmp1,
                                                                                                           int64_t tmp3,
                                                                                                           int64_t tmp5);

void __Client_accept_verification_start_future_drop(int64_t, int64_t boxed);

struct __Client_get_verification_emoji_future_pollReturn __Client_get_verification_emoji_future_poll(int64_t tmp1,
                                                                                                     int64_t tmp3,
                                                                                                     int64_t tmp5);

void __Client_get_verification_emoji_future_drop(int64_t, int64_t boxed);

struct __Client_confirm_verification_key_future_pollReturn __Client_confirm_verification_key_future_poll(int64_t tmp1,
                                                                                                         int64_t tmp3,
                                                                                                         int64_t tmp5);

void __Client_confirm_verification_key_future_drop(int64_t, int64_t boxed);

struct __Client_mismatch_verification_key_future_pollReturn __Client_mismatch_verification_key_future_poll(int64_t tmp1,
                                                                                                           int64_t tmp3,
                                                                                                           int64_t tmp5);

void __Client_mismatch_verification_key_future_drop(int64_t, int64_t boxed);

struct __Client_cancel_verification_key_future_pollReturn __Client_cancel_verification_key_future_poll(int64_t tmp1,
                                                                                                       int64_t tmp3,
                                                                                                       int64_t tmp5);

void __Client_cancel_verification_key_future_drop(int64_t, int64_t boxed);

struct __Client_review_verification_mac_future_pollReturn __Client_review_verification_mac_future_poll(int64_t tmp1,
                                                                                                       int64_t tmp3,
                                                                                                       int64_t tmp5);

void __Client_review_verification_mac_future_drop(int64_t, int64_t boxed);

struct __SyncState_get_to_device_rx_stream_pollReturn __SyncState_get_to_device_rx_stream_poll(int64_t tmp1,
                                                                                               int64_t tmp3,
                                                                                               int64_t tmp5,
                                                                                               int64_t tmp7);

void __SyncState_get_to_device_rx_stream_drop(int64_t, int64_t boxed);

struct __SyncState_get_sync_msg_like_rx_stream_pollReturn __SyncState_get_sync_msg_like_rx_stream_poll(int64_t tmp1,
                                                                                                       int64_t tmp3,
                                                                                                       int64_t tmp5,
                                                                                                       int64_t tmp7);

void __SyncState_get_sync_msg_like_rx_stream_drop(int64_t, int64_t boxed);

uintptr_t __FfiListConversationCreate(void);

void drop_box_FfiListConversation(int64_t, int64_t boxed);

uint32_t __FfiListConversationLen(uintptr_t boxed);

uintptr_t __FfiListConversationElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListConversationRemove(uintptr_t boxed, uint32_t index);

void __FfiListConversationAdd(uintptr_t boxed, uintptr_t element);

void __FfiListConversationInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListFaqCreate(void);

void drop_box_FfiListFaq(int64_t, int64_t boxed);

uint32_t __FfiListFaqLen(uintptr_t boxed);

uintptr_t __FfiListFaqElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListFaqRemove(uintptr_t boxed, uint32_t index);

void __FfiListFaqAdd(uintptr_t boxed, uintptr_t element);

void __FfiListFaqInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListGroupCreate(void);

void drop_box_FfiListGroup(int64_t, int64_t boxed);

uint32_t __FfiListGroupLen(uintptr_t boxed);

uintptr_t __FfiListGroupElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListGroupRemove(uintptr_t boxed, uint32_t index);

void __FfiListGroupAdd(uintptr_t boxed, uintptr_t element);

void __FfiListGroupInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListMemberCreate(void);

void drop_box_FfiListMember(int64_t, int64_t boxed);

uint32_t __FfiListMemberLen(uintptr_t boxed);

uintptr_t __FfiListMemberElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListMemberRemove(uintptr_t boxed, uint32_t index);

void __FfiListMemberAdd(uintptr_t boxed, uintptr_t element);

void __FfiListMemberInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListNewsCreate(void);

void drop_box_FfiListNews(int64_t, int64_t boxed);

uint32_t __FfiListNewsLen(uintptr_t boxed);

uintptr_t __FfiListNewsElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListNewsRemove(uintptr_t boxed, uint32_t index);

void __FfiListNewsAdd(uintptr_t boxed, uintptr_t element);

void __FfiListNewsInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListRoomMessageCreate(void);

void drop_box_FfiListRoomMessage(int64_t, int64_t boxed);

uint32_t __FfiListRoomMessageLen(uintptr_t boxed);

uintptr_t __FfiListRoomMessageElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListRoomMessageRemove(uintptr_t boxed, uint32_t index);

void __FfiListRoomMessageAdd(uintptr_t boxed, uintptr_t element);

void __FfiListRoomMessageInsert(uintptr_t boxed, uint32_t index, uintptr_t element);

uintptr_t __FfiListTagCreate(void);

void drop_box_FfiListTag(int64_t, int64_t boxed);

uint32_t __FfiListTagLen(uintptr_t boxed);

uintptr_t __FfiListTagElementAt(uintptr_t boxed, uint32_t index);

uintptr_t __FfiListTagRemove(uintptr_t boxed, uint32_t index);

void __FfiListTagAdd(uintptr_t boxed, uintptr_t element);

void __FfiListTagInsert(uintptr_t boxed, uint32_t index, uintptr_t element);
