import 'package:atlas_icons/atlas_icons.dart';
import 'package:flutter/cupertino.dart';

class IconModel {
  final IconData iconData;
  final bool isSelected;

  const IconModel({
    required this.iconData,
    this.isSelected = false,
  });
}

List<IconModel> iconsList = [
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safe_bold),
  const IconModel(iconData: Atlas.airplane, isSelected: true),
  const IconModel(iconData: Atlas.washing_machine),
  const IconModel(iconData: Atlas.walkie_talkie_bold),
  const IconModel(iconData: Atlas.receipt_list_thin),
  const IconModel(iconData: Atlas.face_mask),
  const IconModel(iconData: Atlas.zip_file),
  const IconModel(iconData: Atlas.receipt_dollar),
  const IconModel(iconData: Atlas.account_arrows),
  const IconModel(iconData: Atlas.dash_cloud),
  const IconModel(iconData: Atlas.wall),
  const IconModel(iconData: Atlas.question_bold),
  const IconModel(iconData: Atlas.account),
  const IconModel(iconData: Atlas.question_clipboard_thin),
  const IconModel(iconData: Atlas.ice_cream_stick_thin),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safety_glove_thin),
  const IconModel(iconData: Atlas.magnifier_search_account_thin),
  const IconModel(iconData: Atlas.yoga_pose_bold),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safe_bold),
  const IconModel(iconData: Atlas.eraser_bold),
  const IconModel(iconData: Atlas.washing_machine),
  const IconModel(iconData: Atlas.walkie_talkie_bold),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.receipt_list_thin),
  const IconModel(iconData: Atlas.face_mask),
  const IconModel(iconData: Atlas.zip_file),
  const IconModel(iconData: Atlas.receipt_dollar),
  const IconModel(iconData: Atlas.account_arrows),
  const IconModel(iconData: Atlas.dash_cloud),
  const IconModel(iconData: Atlas.wall),
  const IconModel(iconData: Atlas.question_bold),
  const IconModel(iconData: Atlas.account),
  const IconModel(iconData: Atlas.question_clipboard_thin),
  const IconModel(iconData: Atlas.ice_cream_stick_thin),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safety_glove_thin),
  const IconModel(iconData: Atlas.magnifier_search_account_thin),
  const IconModel(iconData: Atlas.yoga_pose_bold),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safe_bold),
  const IconModel(iconData: Atlas.eraser_bold),
  const IconModel(iconData: Atlas.washing_machine),
  const IconModel(iconData: Atlas.walkie_talkie_bold),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.receipt_list_thin),
  const IconModel(iconData: Atlas.face_mask),
  const IconModel(iconData: Atlas.zip_file),
  const IconModel(iconData: Atlas.receipt_dollar),
  const IconModel(iconData: Atlas.account_arrows),
  const IconModel(iconData: Atlas.dash_cloud),
  const IconModel(iconData: Atlas.wall),
  const IconModel(iconData: Atlas.question_bold),
  const IconModel(iconData: Atlas.account),
  const IconModel(iconData: Atlas.question_clipboard_thin),
  const IconModel(iconData: Atlas.ice_cream_stick_thin),
  const IconModel(iconData: Atlas.paperclip_attachment),
  const IconModel(iconData: Atlas.safety_glove_thin),
  const IconModel(iconData: Atlas.magnifier_search_account_thin),
  const IconModel(iconData: Atlas.yoga_pose_bold),
];
