[package]
name = "sari"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]

clap = { version = "4.3.15", features = ["derive"] }
anyhow = "1.0.71"
env_logger = "0.11.7"
uniffi-dart = { workspace = true, features = ["build"] }