# The URL the site will be built for
base_url = "https://docs.acter.global"

title = "ActerDocs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "en"

theme = "adidoks"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Put all your custom variables here
author = "Acter Developers"
github = "https://github.com/acterglobal"
twitter = "https://twitter.com/acterhq"
email = "devs@acter.global"

[[extra.menu.main]]
name = "Users"
section = "user"
url = "/user/getting-started/setting-up/"
weight = 10

[[extra.menu.main]]
name = "Admin"
section = "admin"
url = "/admin/space-admin/introduction/"
weight = 12

[[extra.menu.main]]
name = "Nightly"
section = "nightly"
url = "/nightly/"
weight = 10

[[extra.menu.main]]
name = "Dev"
section = "docs"
url = "/docs/getting-started/setup/"
weight = 15

[[extra.menu.main]]
name = "APIs"
section = "docs"
url = "/docs/dev/api-docs/"
weight = 20


# [[extra.menu.social]]
# name = "Twitter"
# pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
# url = "https://twitter.com/acter"
# weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/acterglobal/a3"
post = "v0.1.0"
weight = 20

# Footer contents
[extra.footer]
info = 'Proudly build with <a href="https://www.getzola.org/">Zola</a> and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'

[[extra.footer.nav]]
name = "Website"
url = "https://acter.global/"
weight = 10

# [[extra.footer.nav]]
# name = "Code of Conduct"
# url = "/docs/contributing/code-of-conduct/"
# weight = 20