on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Flutter Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter:
    strategy:
      matrix:
       include:
          - name: App
            path: ./app
            include_enven: true
          - name: Notifify
            path: packages/acter_notifify
    name: Flutter Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        name: Set up flutter
        with:
          flutter-version: '3.29'
          channel: 'stable'
      - name: Generate env
        working-directory: ${{ matrix.path }}
        if: ${{ matrix.include_enven }}
        run: dart run enven
      - name: Run flutter unit tests
        working-directory: ${{ matrix.path }}
        run: |
          flutter pub get
          flutter test --coverage
      - name: Archieve Golden Failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Golden failures
          retention-days: 2
          path: |
            **/test/**/failures/**/*.*
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          directory: ${{ matrix.path }}/coverage
          flags: unittest
          name: flutter-widget-tests
          token: ${{ secrets.CODECOV_TOKEN }}
