on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

name: Native

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Clippy ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Core
            package: acter-core
            clippy_extras: --tests
          - name: Matrix Core
            package: acter-matrix
            clippy_extras: --tests
          - name: SDK
            package: acter
            needs_flutter: true
            clippy_extras: --tests --features testing
          - name: file-event-cache
            package: matrix-sdk-store-file-event-cache
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: subosito/flutter-action@v2
        if: ${{matrix.needs_flutter}}
        with:
          flutter-version: '3.32'
          channel: 'stable'
      - name: Run Clippy
        run: cargo clippy  -p ${{matrix.package}} ${{matrix.clippy_extras}} -- -D warnings

  test:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Core
            package: acter-core
          - name: Matrix Core
            package: acter-matrix
          # - name: file-event-cache
          #   package: matrix-sdk-store-file-event-cache
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,nextest@0.9.98
      - name: Test
        run: cargo llvm-cov --lcov --output-path lcov.info nextest -p ${{matrix.package}}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          flags: unittest
          name: rust-unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    name: Release Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: SDK
            package: acter
            needs_flutter: true
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: subosito/flutter-action@v2
        if: ${{matrix.needs_flutter}}
        with:
          flutter-version: '3.32'
          channel: 'stable'
      - name: Release Build
        run: cargo build -p ${{matrix.package}} --release


  ffigen:
    name: FFI-Gen up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32'
          channel: 'stable'
      - name: Install supported rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: "Build FFI interface"
        run: cargo make ffi
      - name: "Check file is no different"
        run: git diff -w --exit-code packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart packages/rust_sdk/lib/acter.dart
