name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  CLABot:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: roblox/cla-assistant@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use-remote-repo: true
          remote-repo-name: "acterglobal/cla-store"
          path-to-signatures: "signatures/version1.json"
          url-to-cladocument: "https://github.com/acterglobal/a3/blob/main/.github/cla/CLA.md"
          # This branch can't have protections, commits are made directly to the specified branch.
          branch: "main"
          whitelist: gtalha07,bitfriend,dependabot[bot]
          blockchain-storage-flag: false
          remote-repo-pat: ${{ secrets.CLA_BOT_PAT }}
