name: Nightly builds checker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  run_checker:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' && steps.check-changelog-files.outputs.has-changelog-files == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true # fetch the tags
      - name: Check for new commits since last nightly
        id: check-new-commits
        shell: bash
        run: |
          if [ `git diff --name-only nightly-latest app native .changes | wc -l` -ne 0 ]; then
            echo "has-new-commits=true"  >> $GITHUB_OUTPUT ;
            echo "has-new-commits=true";
          else
            echo "has-new-commits=false" >> $GITHUB_OUTPUT ;
            echo "has-new-commits=false";
          fi
      - name: Check whether any changelog files are present
        id: check-changelog-files
        shell: bash
        run: |
            files=$(shopt -s nullglob;shopt -s dotglob;echo .changes/*.md)
            if (( ${#files} ))
            then
              echo "has-changelog-files=true"  >> $GITHUB_OUTPUT ;
              echo "has-changelog-files=true";
            else
              echo "has-changelog-files=false" >> $GITHUB_OUTPUT ;
              echo "has-changelog-files=false";
            fi

  tags:
    runs-on: ubuntu-latest
    needs:
     - run_checker
    if: ${{ needs.run_checker.outputs.should_run != 'false' }}
    steps:
      - id: tag
        run: echo "${{ needs.run_checker.outputs.should_run}}"
      - id: build_num
        run: echo "${{ needs.run_checker.outputs.should_run != 'false' }}"
  