on:
  release:
    types: 
      # - released   # use this for actual releases
      - prereleased  # use this to trigger on test releases


jobs:
  microsoft-store:
    runs-on: windows-latest
    environment: release
    steps:

      - uses: dsaltares/fetch-gh-release-asset@master
        name: Download MSIX
        with:
          version: {{github.release.id}}
          regex: true
          file: "*.msix"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dsaltares/fetch-gh-release-asset@master
        name: Download changelogs and notes
        with:
          version: {{github.release.id}}
          regex: true
          file: "*.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup MS Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1

      - name: Configure MS Store credentials
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.MS_STORE_SELLER_ID }}
