name: Publish Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.target || 'all' }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Provide the version for this release'
        required: true
        type: string
      prev_tag:
        description: 'The tag to compare the changelog to'
        required: false
        type: string
      target:
        description: 'Build only Target'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android
          - macos
          - linux
          - windows-exe
          - windows-msix
      custom_title:
        description: 'You want a custom title for the release?'
        required: false
        type: string

  schedule:
   - cron: 0 3 * * 4

jobs:
  run_checker:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ inputs.new_version != null || steps.check-new-commits.outputs.has-new-commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history and tags
      - name: Check for new commits since last release
        id: check-new-commits
        shell: bash
        run: |
          if [ `git diff --name-only ${{ inputs.prev_tag || 'release-latest' }} -- app native .changes | wc -l` -ne 0 ]; then
            echo "has-new-commits=true"  >> $GITHUB_OUTPUT ;
          else
            echo "has-new-commits=false" >> $GITHUB_OUTPUT ;
          fi

  tags:
    runs-on: ubuntu-latest
    needs:
     - run_checker
    if: ${{ needs.run_checker.outputs.should_run != 'false' }}
    # Map a step output to a job output
    outputs:
      tag: v${{ inputs.new_version || steps.version.outputs.version }}
      version: ${{ inputs.new_version || steps.version.outputs.version }}
      build_num: ${{ steps.build_num.outputs.build_num }}
      prev_tag: ${{ inputs.prev_tag || 'release-latest' }}
      targets: ${{ inputs.target || 'all' }}
      release_title: ${{ inputs.custom_title || 'Release'}}
    steps:
      - id: version
        # the suffix 0 allows us to provide up to 9 more hotfixes on the same day
        run: echo "version=`date +1.%y.%-m%d0`" >> $GITHUB_OUTPUT
      - id: build_num
        run: echo "build_num=`date +%s`" >> $GITHUB_OUTPUT
  
  build:
    uses: ./.github/workflows/actions/build-app.yml
    needs:
     - tags
    with:
      build_num: ${{ needs.tags.outputs.build_num }}
      version: ${{ needs.tags.outputs.version }}
      release_title: ${{ needs.tags.outputs.release_title }} ${{ needs.tags.outputs.tag }}
      release_tag: ${{ needs.tags.outputs.tag }}
      target: ${{ needs.tags.outputs.targets }}
    secrets: inherit

 ######  ##     ##    ###    ##    ##  ######   ######## ##        #######   ######   
##    ## ##     ##   ## ##   ###   ## ##    ##  ##       ##       ##     ## ##    ##  
##       ##     ##  ##   ##  ####  ## ##        ##       ##       ##     ## ##        
##       ######### ##     ## ## ## ## ##   #### ######   ##       ##     ## ##   #### 
##       ##     ## ######### ##  #### ##    ##  ##       ##       ##     ## ##    ##  
##    ## ##     ## ##     ## ##   ### ##    ##  ##       ##       ##     ## ##    ##  
 ######  ##     ## ##     ## ##    ##  ######   ######## ########  #######   ######  

  changelog:
    environment: release
    runs-on: ubuntu-latest
    name: Generate Changelog
    needs:
      - tags
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Generate Changelog
        run: |
          git fetch --prune --unshallow --tags
          cargo run -p mr_minutes -- --since ${{ needs.tags.outputs.prev_tag }} --output CHANGELOG-generated.md
          echo "# Changes since ${{ needs.tags.outputs.prev_tag }} " > CHANGELOG.md
          cat CHANGELOG-generated.md >> CHANGELOG.md

      - uses: actions/upload-artifact@v3
        name: "Upload Changelog"
        with:
          name: Changelog
          path: CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ needs.tags.outputs.release_title }} ${{ needs.tags.outputs.tag }}
          tag_name: ${{ needs.tags.outputs.tag }}
          generate_release_notes: false
          body_path: CHANGELOG.md
          files: CHANGELOG.md

##     ##  ######      ######  ########  #######  ########  ######## 
###   ### ##    ##    ##    ##    ##    ##     ## ##     ## ##       
#### #### ##          ##          ##    ##     ## ##     ## ##       
## ### ##  ######      ######     ##    ##     ## ########  ######   
##     ##       ##          ##    ##    ##     ## ##   ##   ##       
##     ## ##    ##    ##    ##    ##    ##     ## ##    ##  ##       
##     ##  ######      ######     ##     #######  ##     ## ######## 


  microsoft-store:
    runs-on: windows-latest
    environment: release
    needs:
      - tags
      - build
    steps:

      - uses: actions/download-artifact@v3
        with:
          name: Windows msix
      - name: Create Archive
        run: |
          Rename-Item -Path acter-windows-${{ needs.tags.outputs.version }}.msix  -NewName acter.msix
          Compress-Archive -Path acter.msix acter.zip

      - name: setup storebroker
        run: |
          Install-Module StoreBroker -Force
          Import-Module StoreBroker
      # do the submission
      - name: submit to MSStore via StoreBroker
        env:
          TENANTID: ${{ secrets.AZURE_AD_TENANT_ID }}
          CLIENTID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          CLIENTSECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          MS_STORE_APP_ID: ${{ secrets.MS_STORE_APP_ID }}
        run: |
            $DebugPreference = 'Continue'
            # prepare te package
            Write-Debug "Logging in"
            # login with the StoreBroker
            $sec = ConvertTo-SecureString $env:CLIENTSECRET -AsPlainText -Force
            $cred = New-Object System.Management.Automation.PSCredential $env:CLIENTID, $sec
            Set-StoreBrokerAuthentication -TenantId $env:TENANTID -Credential $cred -Verbose
            Write-Debug "Logged in. Preparing submission"
            # create the submission and add new package
            $sub = New-ApplicationSubmission -AppId $env:MS_STORE_APP_ID -Force -Verbose
            $sub.applicationPackages | ForEach-Object { $_.fileStatus = "PendingDelete" }
            $pkg = $sub.applicationPackages[0].PSObject.Copy()
            $pkg.fileName = "acter.msix"
            $pkg.fileStatus = "PendingUpload"
            $pkg.PSObject.Properties.Remove("version")
            $pkg.PSObject.Properties.Remove("id")
            $sub.applicationPackages += $pkg
            Write-Debug "Setting Submission ID"
            Set-ApplicationSubmission -AppId $env:MS_STORE_APP_ID -UpdatedSubmission $sub
            Write-Debug "Setting Submission Package"
            Set-SubmissionPackage -PackagePath 'acter.zip' -UploadUrl ($sub.fileUploadUrl)
            Write-Debug "Completing submission"
            Complete-ApplicationSubmission -AppId $env:MS_STORE_APP_ID -SubmissionId ($sub.id)
            Write-Debug "Submitted successfully"


########  ##          ###    ##    ##     ######  ########  #######  ########  ######## 
##     ## ##         ## ##    ##  ##     ##    ##    ##    ##     ## ##     ## ##       
##     ## ##        ##   ##    ####      ##          ##    ##     ## ##     ## ##       
########  ##       ##     ##    ##        ######     ##    ##     ## ########  ######   
##        ##       #########    ##             ##    ##    ##     ## ##   ##   ##       
##        ##       ##     ##    ##       ##    ##    ##    ##     ## ##    ##  ##       
##        ######## ##     ##    ##        ######     ##     #######  ##     ## ######## 


  google-play-store:
    runs-on: ubuntu-latest
    environment: release
    needs:
      - tags
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Android
      - uses: actions/download-artifact@v3
        with:
          name: Android-debug-symbols
      - name: Release Build to playstore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: global.acter.a3
          releaseName: ${{ needs.tags.outputs.tag }}
          releaseFiles: app-release.aab
          debugSymbols: "*.symbols"
          track: beta
          status: completed


####  #######   ######        ###    ########  ########   ######  ########  #######  ########  ######## 
 ##  ##     ## ##    ##      ## ##   ##     ## ##     ## ##    ##    ##    ##     ## ##     ## ##       
 ##  ##     ## ##           ##   ##  ##     ## ##     ## ##          ##    ##     ## ##     ## ##       
 ##  ##     ##  ######     ##     ## ########  ########   ######     ##    ##     ## ########  ######   
 ##  ##     ##       ##    ######### ##        ##              ##    ##    ##     ## ##   ##   ##       
 ##  ##     ## ##    ##    ##     ## ##        ##        ##    ##    ##    ##     ## ##    ##  ##       
####  #######   ######     ##     ## ##        ##         ######     ##     #######  ##     ## ######## 


  apple-store-ios:
    runs-on: macos-latest
    environment: release
    needs:
      - tags
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: iOS

      - name: Upload to App Store
        env:
          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
        run: |
          mkdir private_keys
          echo -n "$APPLE_API_KEY_BASE64" | base64 --decode --output "private_keys/AuthKey_$APPLE_API_KEY_ID.p8"
          xcrun altool --upload-app --type ios --file *.ipa \
              --apiKey "$APPLE_API_KEY_ID" --apiIssuer "$APPLE_ISSUER_ID"
        shell: bash


##     ##    ###     ######        ###    ########  ########   ######  ########  #######  ########  ######## 
###   ###   ## ##   ##    ##      ## ##   ##     ## ##     ## ##    ##    ##    ##     ## ##     ## ##       
#### ####  ##   ##  ##           ##   ##  ##     ## ##     ## ##          ##    ##     ## ##     ## ##       
## ### ## ##     ## ##          ##     ## ########  ########   ######     ##    ##     ## ########  ######   
##     ## ######### ##          ######### ##        ##              ##    ##    ##     ## ##   ##   ##       
##     ## ##     ## ##    ##    ##     ## ##        ##        ##    ##    ##    ##     ## ##    ##  ##       
##     ## ##     ##  ######     ##     ## ##        ##         ######     ##     #######  ##     ## ######## 


  apple-store-mac:
    runs-on: macos-latest
    environment: release
    needs:
      - tags
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: MacOS
      - name: Unlock git-crypt
        run: |
          brew install git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 --decode > .github/assets/git-crypt-key
          git-crypt unlock .github/assets/git-crypt-key
          echo "Files found:"
          git-crypt status -e

      # Install the Apple certificate and provisioning profile
      - name: Install the Apple certificates
        env:
          P12_PASSWORD: ${{ secrets.BUILD_CERTS_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "starting in $RUNNER_TEMP"
          # create variables
          CERTIFICATE_PATH=".github/assets/build_certificates.p12"
          KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"
          echo "vars set"
          # import certificate and provisioning profile from secrets
          # create temporary keychain
          echo "creating keychain"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          echo "setting keychain"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          echo "unlocking keychain"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          # import certificate to keychain
          echo "importing certificate"
          security import "$CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          echo "listing keychains"
          security list-keychain -d user -s "$KEYCHAIN_PATH"

      - name: Install the Apple provisioning profile
        run: |
          echo "Installing provision profiles"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          cp .github/assets/provision_profiles/* ~/Library/MobileDevice/Provisioning\ Profiles/
          ls -ltas ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Upload to App Store
        env:
          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
        run: |
          mkdir private_keys
          echo -n "$APPLE_API_KEY_BASE64" | base64 --decode --output "private_keys/AuthKey_$APPLE_API_KEY_ID.p8"
          ls -ltas private_keys
          xcrun altool --upload-app --type macos --file acter-macosx-${{ needs.tags.outputs.version }}.pkg \
              --bundle-id global.acter.a3 \
              --apiKey "$APPLE_API_KEY_ID" \
              --apiIssuer "$APPLE_ISSUER_ID"
        shell: bash

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/*
          rm .github/assets/git-crypt-key


   ###    ########   ######  ##     ##       ###    ##     ## ########  
  ## ##   ##     ## ##    ## ##     ##      ## ##   ##     ## ##     ## 
 ##   ##  ##     ## ##       ##     ##     ##   ##  ##     ## ##     ## 
##     ## ########  ##       #########    ##     ## ##     ## ########  
######### ##   ##   ##       ##     ##    ######### ##     ## ##   ##   
##     ## ##    ##  ##    ## ##     ##    ##     ## ##     ## ##    ##  
##     ## ##     ##  ######  ##     ##    ##     ##  #######  ##     ## 



  publish_aur:
    environment: release
    needs:
      - tags
      - build
    name: Publish AUR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Linux x64
      - name: Create PKGBUILD file
        run: |
          cp app/linux/packaging/aur/PKGBUILD PKGBUILD
          sed -i "s/%{{TAG}}%/${{ needs.tags.outputs.version }}/g" PKGBUILD
          VERSION=$(echo ${{ needs.tags.outputs.version }} | sed "s/-/./g")
          sed -i "s/%{{VERSION}}%/$VERSION/g" PKGBUILD
          sed -i "s/%{{PKGREL}}%/2/g" PKGBUILD
          sed -i "s/%{{LINUX_MD5}}%/`md5sum acter-linux-x64-${{ needs.tags.outputs.version }}.tar.bz2  | awk '{print $1}'`/g" PKGBUILD
      - uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        name: Publish to AUR
        with:
          pkgname: acter-bin
          pkgbuild: ./PKGBUILD
          commit_username: Sari
          commit_email: sari@acter.global
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Updated to ${{ needs.tags.outputs.version }}



 ######   #### ######## ##     ## ##     ## ########     ########  ##     ## ########  ##       ####  ######  ##     ## 
##    ##   ##     ##    ##     ## ##     ## ##     ##    ##     ## ##     ## ##     ## ##        ##  ##    ## ##     ## 
##         ##     ##    ##     ## ##     ## ##     ##    ##     ## ##     ## ##     ## ##        ##  ##       ##     ## 
##   ####  ##     ##    ######### ##     ## ########     ########  ##     ## ########  ##        ##   ######  ######### 
##    ##   ##     ##    ##     ## ##     ## ##     ##    ##        ##     ## ##     ## ##        ##        ## ##     ## 
##    ##   ##     ##    ##     ## ##     ## ##     ##    ##        ##     ## ##     ## ##        ##  ##    ## ##     ## 
 ######   ####    ##    ##     ##  #######  ########     ##         #######  ########  ######## ####  ######  ##     ## 

  publish:
    environment: nightly
    runs-on: ubuntu-latest
    name: Publish
    # if: ${{ github.event.schedule }}
    needs:
      - tags
      - build
      - changelog
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/download-artifact@v3
        with:
          name: Changelog

      - name: Configure git
        run: | # make sure we have the tags and all
          git fetch --prune --unshallow --tags
          git config --global user.name 'Sari'
          git config --global user.email 'acter-sari@users.noreply.github.com'

      - name: "Generate docs"
        run: |
          echo "+++" > docs/content/releases/${{ needs.tags.outputs.version }}.md
          echo "title = \" ${{ needs.tags.outputs.tag }}\"" >> docs/content/releases/${{ needs.tags.outputs.version }}.md
          echo "template = \"releases/release.html\"" >> docs/content/releases/${{ needs.tags.outputs.version }}.md
          echo "date = `date +%Y-%m-%d`" >> docs/content/releases/${{ needs.tags.outputs.version }}.md
          echo "+++" >> docs/content/releases/${{ needs.tags.outputs.version }}.md
          echo "" >> docs/content/releases/${{ needs.tags.outputs.version }}.md
          cat CHANGELOG.md >> docs/content/releases/${{ needs.tags.outputs.version }}.md

      - name: Clear old docs
        continue-on-error: true
        run: |
          git rm .changes/*.md
          git commit -m "Clearing .changes for ${{ needs.tags.outputs.version }}"

      - name: "Update flatpack version"
        run : |
          bash app/flatpak/add_release_info.sh ${{ needs.tags.outputs.version }}
          git add app/flatpak/global.acter.a3.metainfo_versions.xml

      - name: Tag for release
        run: |
          git add "docs/content/releases/${{ needs.tags.outputs.version }}.md"
          echo "Add release ${{ needs.tags.outputs.tag }}"
          git commit -m "Releasing ${{ needs.tags.outputs.tag }}"
          git tag ${{ needs.tags.outputs.tag }}
          git push origin main ${{ needs.tags.outputs.tag }} release-latest

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # publish this full release now
          draft: true
          generate_release_notes: false
          name: ${{ needs.tags.outputs.release_title }} ${{ needs.tags.outputs.version }}
          tag_name: ${{ needs.tags.outputs.tag }}
          body_path: CHANGELOG.md
          make_latest: true
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
