on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Flutter Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        name: Set up flutter
        with:
          channel: 'stable'
      - name: Run flutter unit tests
        working-directory: app
        run: flutter test
